[package]
name = "learning-macroquad"
version = "0.1.0"
edition = "2024"

[profile.dev.package.'*']
opt-level = 3

[dependencies]
macroquad = { version = "0.4.14", features = ["audio"] }
macroquad-particles = "0.2.2"
